In [1]:
import os
os.listdir()

['.env',
 '.git',
 '.gitignore',
 '.venv',
 '.vscode',
 'activities.csv',
 'alertas',
 'assets',
 'datasets',
 'datetime',
 'encontrarRede',
 'environment.yml',
 'food.csv',
 'functions',
 'limpeza.xlsx',
 'Linkedin-raspagem',
 'logs',
 'notasLuciana.md',
 'notebooks',
 'pyproject.toml',
 'pythonic',
 'readme.md',
 'resizeLogo',
 'src',
 'testes',
 'tests',
 'validacao']

In [2]:
import pandas as pd

xls = pd.ExcelFile("limpeza.xlsx")
print(xls.sheet_names)

['tema']

In [3]:
xls

In [4]:
df = pd.read_excel("limpeza.xlsx", sheet_name="tema")

In [5]:
df

         ASSUNTO
0          Leads
1       Analises
2        Cotação
3       Proposta
4       Analises
..           ...
74     Sucursais
75    Corretores
76  Funcionários
77      Segmento
78      Agencias

[79 rows x 1 columns]

In [6]:
# Remove linhas duplicadas
df = df.drop_duplicates()

In [7]:
df

                    ASSUNTO
0                     Leads
1                  Analises
2                   Cotação
3                  Proposta
5                 Campanhas
6                    vendas
7                  Comissão
9                Pagamentos
10             Cancelamento
11                 Sinistro
12                  Endosso
13                 Vistoria
14            Manifestações
16                Pós venda
17                Renovação
18                      NPS
19                Terceiras
20                 Serviços
21                 Produtos
22               Coberturas
23               Angariação
28         Exames-consultas
29                Reembolso
30               Internação
36         Rede-Credenciada
42             Assistencias
50             Contribuição
52                  Resgate
53            Portabilidade
54            Beneficiarios
63  Fundos de Investimentos
65                 Sorteios
74                Sucursais
75               Corretores
76             Funcionários
77                 Segmento
78                 Agencias

In [8]:
df.columns

Index(['ASSUNTO'], dtype='object')

In [9]:
# Cada linha vira uma string separada por vírgula
linhas = df.astype(str).apply(lambda row: ",".join(row), axis=1)

# Visualizar as primeiras linhas
print(linhas.head())

0        Leads
1     Analises
2      Cotação
3     Proposta
5    Campanhas
dtype: object

In [10]:
for linha in linhas:
    print(linha)

Leads
Analises
Cotação
Proposta
Campanhas
vendas
Comissão
Pagamentos
Cancelamento
Sinistro
Endosso
Vistoria
Manifestações
Pós venda
Renovação
NPS
Terceiras
Serviços
Produtos
Coberturas
Angariação
Exames-consultas
Reembolso
Internação
Rede-Credenciada
Assistencias
Contribuição
Resgate
Portabilidade
Beneficiarios
Fundos de Investimentos
Sorteios
Sucursais
Corretores
Funcionários
Segmento
Agencias

In [11]:
##%pip install unidecode

In [12]:
from unidecode import unidecode

# Remove acentos de todas as células de texto
df = df.applymap(lambda x: unidecode(x) if isinstance(x, str) else x)

C:\Users\luciana.santos\AppData\Local\Temp\ipykernel_43544\2283120657.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: unidecode(x) if isinstance(x, str) else x)

In [13]:
df["ASSUNTO"] = df["ASSUNTO"].apply(lambda x: unidecode(x) if isinstance(x, str) else x)

In [14]:
df

                    ASSUNTO
0                     Leads
1                  Analises
2                   Cotacao
3                  Proposta
5                 Campanhas
6                    vendas
7                  Comissao
9                Pagamentos
10             Cancelamento
11                 Sinistro
12                  Endosso
13                 Vistoria
14            Manifestacoes
16                Pos venda
17                Renovacao
18                      NPS
19                Terceiras
20                 Servicos
21                 Produtos
22               Coberturas
23               Angariacao
28         Exames-consultas
29                Reembolso
30               Internacao
36         Rede-Credenciada
42             Assistencias
50             Contribuicao
52                  Resgate
53            Portabilidade
54            Beneficiarios
63  Fundos de Investimentos
65                 Sorteios
74                Sucursais
75               Corretores
76             Funcionarios
77                 Segmento
78                 Agencias

In [15]:
df["ASSUNTO"] = df["ASSUNTO"].str.upper()

In [16]:
df

                    ASSUNTO
0                     LEADS
1                  ANALISES
2                   COTACAO
3                  PROPOSTA
5                 CAMPANHAS
6                    VENDAS
7                  COMISSAO
9                PAGAMENTOS
10             CANCELAMENTO
11                 SINISTRO
12                  ENDOSSO
13                 VISTORIA
14            MANIFESTACOES
16                POS VENDA
17                RENOVACAO
18                      NPS
19                TERCEIRAS
20                 SERVICOS
21                 PRODUTOS
22               COBERTURAS
23               ANGARIACAO
28         EXAMES-CONSULTAS
29                REEMBOLSO
30               INTERNACAO
36         REDE-CREDENCIADA
42             ASSISTENCIAS
50             CONTRIBUICAO
52                  RESGATE
53            PORTABILIDADE
54            BENEFICIARIOS
63  FUNDOS DE INVESTIMENTOS
65                 SORTEIOS
74                SUCURSAIS
75               CORRETORES
76             FUNCIONARIOS
77                 SEGMENTO
78                 AGENCIAS

In [17]:
# Cada linha vira uma string separada por vírgula
linhas = df.astype(str).apply(lambda row: ",".join(row), axis=1)

# Visualizar as primeiras linhas
print(linhas.head())

0        LEADS
1     ANALISES
2      COTACAO
3     PROPOSTA
5    CAMPANHAS
dtype: object

In [18]:
df_transposto = df.T
print(df_transposto.head())

            0         1        2         3          5       6         7   \
ASSUNTO  LEADS  ANALISES  COTACAO  PROPOSTA  CAMPANHAS  VENDAS  COMISSAO

                 9             10        11  ...       52             53  \
ASSUNTO  PAGAMENTOS  CANCELAMENTO  SINISTRO  ...  RESGATE  PORTABILIDADE

                    54                       63        65         74  \
ASSUNTO  BENEFICIARIOS  FUNDOS DE INVESTIMENTOS  SORTEIOS  SUCURSAIS

                 75            76        77        78
ASSUNTO  CORRETORES  FUNCIONARIOS  SEGMENTO  AGENCIAS

[1 rows x 37 columns]

In [20]:
linha = df["ASSUNTO"].tolist()
print(linha)

['LEADS', 'ANALISES', 'COTACAO', 'PROPOSTA', 'CAMPANHAS', 'VENDAS', 'COMISSAO', 'PAGAMENTOS', 'CANCELAMENTO', 'SINISTRO', 'ENDOSSO', 'VISTORIA', 'MANIFESTACOES', 'POS VENDA', 'RENOVACAO', 'NPS', 'TERCEIRAS', 'SERVICOS', 'PRODUTOS', 'COBERTURAS', 'ANGARIACAO', 'EXAMES-CONSULTAS', 'REEMBOLSO', 'INTERNACAO', 'REDE-CREDENCIADA', 'ASSISTENCIAS', 'CONTRIBUICAO', 'RESGATE', 'PORTABILIDADE', 'BENEFICIARIOS', 'FUNDOS DE INVESTIMENTOS', 'SORTEIOS', 'SUCURSAIS', 'CORRETORES', 'FUNCIONARIOS', 'SEGMENTO', 'AGENCIAS']

In [21]:
linha = ",".join(df["ASSUNTO"].astype(str))
print(linha)

LEADS,ANALISES,COTACAO,PROPOSTA,CAMPANHAS,VENDAS,COMISSAO,PAGAMENTOS,CANCELAMENTO,SINISTRO,ENDOSSO,VISTORIA,MANIFESTACOES,POS VENDA,RENOVACAO,NPS,TERCEIRAS,SERVICOS,PRODUTOS,COBERTURAS,ANGARIACAO,EXAMES-CONSULTAS,REEMBOLSO,INTERNACAO,REDE-CREDENCIADA,ASSISTENCIAS,CONTRIBUICAO,RESGATE,PORTABILIDADE,BENEFICIARIOS,FUNDOS DE INVESTIMENTOS,SORTEIOS,SUCURSAIS,CORRETORES,FUNCIONARIOS,SEGMENTO,AGENCIAS

In [26]:
mapa = {
    "VENDA": "VENDAS",
    "CAMPANHAS": "CAMPANHAS",
    "OUTROS": "SERVICOS"   # exemplo de substituição

}

df["ASSUNTO"] = df["ASSUNTO"].replace(mapa)

In [23]:
novos_assuntos = [
    'LEADS', 'ANALISES', 'COTACAO', 'PROPOSTA', 'CAMPANHAS', 'VENDAS', 'COMISSAO',
    'PAGAMENTOS', 'CANCELAMENTO', 'SINISTRO', 'ENDOSSO', 'VISTORIA', 'MANIFESTACOES',
    'POS VENDA', 'RENOVACAO', 'NPS', 'TERCEIRAS', 'SERVICOS', 'PRODUTOS', 'COBERTURAS',
    'ANGARIACAO', 'EXAMES-CONSULTAS', 'REEMBOLSO', 'INTERNACAO', 'REDE-CREDENCIADA',
    'ASSISTENCIAS', 'CONTRIBUICAO', 'RESGATE', 'PORTABILIDADE', 'BENEFICIARIOS',
    'FUNDOS DE INVESTIMENTOS', 'SORTEIOS', 'SUCURSAIS', 'CORRETORES', 'FUNCIONARIOS',
    'SEGMENTO', 'AGENCIAS'
]

# Exemplo: substituir todos os valores antigos por uma escolha aleatória da lista
import numpy as np
df["ASSUNTO"] = np.random.choice(novos_assuntos, size=len(df))

In [24]:
df["ASSUNTO_NOVO"] = np.random.choice(novos_assuntos, size=len(df))

In [25]:
df

                    ASSUNTO      ASSUNTO_NOVO
0                   ENDOSSO         TERCEIRAS
1                  PRODUTOS  REDE-CREDENCIADA
2                INTERNACAO  REDE-CREDENCIADA
3          REDE-CREDENCIADA           COTACAO
5              ASSISTENCIAS      ASSISTENCIAS
6                 POS VENDA         TERCEIRAS
7                  COMISSAO               NPS
9                   ENDOSSO     BENEFICIARIOS
10                  COTACAO             LEADS
11                 SINISTRO          VISTORIA
12                REEMBOLSO        COBERTURAS
13                      NPS     MANIFESTACOES
14            BENEFICIARIOS      ASSISTENCIAS
16            BENEFICIARIOS             LEADS
17             CONTRIBUICAO             LEADS
18               PAGAMENTOS     BENEFICIARIOS
19            BENEFICIARIOS          AGENCIAS
20             FUNCIONARIOS     BENEFICIARIOS
21                 VISTORIA     PORTABILIDADE
22                 ANALISES          AGENCIAS
23         REDE-CREDENCIADA        CORRETORES
28  FUNDOS DE INVESTIMENTOS           RESGATE
29         EXAMES-CONSULTAS         POS VENDA
30             FUNCIONARIOS        CORRETORES
36                 SORTEIOS      CANCELAMENTO
42                 PROPOSTA          AGENCIAS
50                REEMBOLSO           RESGATE
52                 ANALISES          ANALISES
53                 ANALISES          VISTORIA
54             FUNCIONARIOS        PAGAMENTOS
63            BENEFICIARIOS        PAGAMENTOS
65                    LEADS            VENDAS
74                CAMPANHAS             LEADS
75                  RESGATE         CAMPANHAS
76                POS VENDA         RENOVACAO
77             CANCELAMENTO          PROPOSTA
78                 SORTEIOS      ASSISTENCIAS

In [27]:
assuntos = [
    'LEADS', 'ANALISES', 'COTACAO', 'PROPOSTA', 'CAMPANHAS', 'VENDAS', 'COMISSAO',
    'PAGAMENTOS', 'CANCELAMENTO', 'SINISTRO', 'ENDOSSO', 'VISTORIA', 'MANIFESTACOES',
    'POS VENDA', 'RENOVACAO', 'NPS', 'TERCEIRAS', 'SERVICOS', 'PRODUTOS', 'COBERTURAS',
    'ANGARIACAO', 'EXAMES-CONSULTAS', 'REEMBOLSO', 'INTERNACAO', 'REDE-CREDENCIADA',
    'ASSISTENCIAS', 'CONTRIBUICAO', 'RESGATE', 'PORTABILIDADE', 'BENEFICIARIOS',
    'FUNDOS DE INVESTIMENTOS', 'SORTEIOS', 'SUCURSAIS', 'CORRETORES', 'FUNCIONARIOS',
    'SEGMENTO', 'AGENCIAS'
]

# Colocar cada item entre aspas
assuntos_com_aspas = [f'"{item}"' for item in assuntos]

print(assuntos_com_aspas)

['"LEADS"', '"ANALISES"', '"COTACAO"', '"PROPOSTA"', '"CAMPANHAS"', '"VENDAS"', '"COMISSAO"', '"PAGAMENTOS"', '"CANCELAMENTO"', '"SINISTRO"', '"ENDOSSO"', '"VISTORIA"', '"MANIFESTACOES"', '"POS VENDA"', '"RENOVACAO"', '"NPS"', '"TERCEIRAS"', '"SERVICOS"', '"PRODUTOS"', '"COBERTURAS"', '"ANGARIACAO"', '"EXAMES-CONSULTAS"', '"REEMBOLSO"', '"INTERNACAO"', '"REDE-CREDENCIADA"', '"ASSISTENCIAS"', '"CONTRIBUICAO"', '"RESGATE"', '"PORTABILIDADE"', '"BENEFICIARIOS"', '"FUNDOS DE INVESTIMENTOS"', '"SORTEIOS"', '"SUCURSAIS"', '"CORRETORES"', '"FUNCIONARIOS"', '"SEGMENTO"', '"AGENCIAS"']

In [28]:
resultado = ",".join([f'"{item}"' for item in assuntos])
print(resultado)

"LEADS","ANALISES","COTACAO","PROPOSTA","CAMPANHAS","VENDAS","COMISSAO","PAGAMENTOS","CANCELAMENTO","SINISTRO","ENDOSSO","VISTORIA","MANIFESTACOES","POS VENDA","RENOVACAO","NPS","TERCEIRAS","SERVICOS","PRODUTOS","COBERTURAS","ANGARIACAO","EXAMES-CONSULTAS","REEMBOLSO","INTERNACAO","REDE-CREDENCIADA","ASSISTENCIAS","CONTRIBUICAO","RESGATE","PORTABILIDADE","BENEFICIARIOS","FUNDOS DE INVESTIMENTOS","SORTEIOS","SUCURSAIS","CORRETORES","FUNCIONARIOS","SEGMENTO","AGENCIAS"